### ISSUE TITLE
如何训练呢？

### ISSUE THREAD

**Issue by zhangjingling** [HuangFJ/figocr#1]
我想知道如何训练模型呢？能否公布一下训练代码。谢谢

**Comment by HuangFJ** [comment]
### 第一步准备数据
先准备数据，然后制成一份索引文件，假设是`labels.txt`：
```
123     dataset/123.jpg
2345    dataset/2345.jpg
...
```
第一列是标注，第二列是图片地址，列和列之间用`'\t'`符分隔。然后在`src/model/dataset.py`源码中将：
```python
        # 本地数据集
        # root=Path('drive/My Drive/cv/images/dataset/labels.txt')
        # line = 0
        # with open(root) as f:
        #     for l in f:
        #         line += 1
        #         if train:
        #             if line % 20 == 0:
        #                 continue
        #         else:
        #             if line % 20 != 0:
        #                 continue

        #         fn, label = l.strip().split('\t')
        #         fn = root.parent.joinpath('images', fn)
        #         self.items.append((str(fn), label))
```
这段注释去掉，将`drive/My Drive/cv/images/dataset/labels.txt`改成你自己的`labels.txt`文件地址。这里面的训练数据和验证数据的数量比例是`20:1`，要按自己情况调整。
### 第二步开始学习
```python
model = OCRModel()
model.evolution()
model.save_checkpoint('path/to/your/model.pth')
```
上面的学习步骤使用了默认参数。实际上除了`OCRModel`的`evolution`方法的参数可以自己定外，还有其他一些参数可以自己改，比如：
- 你可以修改`src/model/vocabulary.py`中的`vocabulary`，定义自己的字符集（分类）；
- 你可以修改`OCRModel`的`input_shape`的`320`，假如你要识别的图片序列超过了20个字符（width=16*序列长度）；
- 你可以修改`OCRModel`的`batch_size`。

**Comment by zhangjingling** [comment]
> ### 第一步准备数据
> 先准备数据，然后制成一份索引文件，假设是`labels.txt`：
> 
> ```
> dataset/123.jpg   123
> dataset/2345.jpg  2345
> ...
> ```
> 
> 第一列是图片地址，第二列是标注，列和列之间用`'\t'`符分隔。然后在`src/model/dataset.py`源码中将：
> 
> ```python
>         # 本地数据集
>         # root=Path('drive/My Drive/cv/images/dataset/labels.txt')
>         # line = 0
>         # with open(root) as f:
>         #     for l in f:
>         #         line += 1
>         #         if train:
>         #             if line % 20 == 0:
>         #                 continue
>         #         else:
>         #             if line % 20 != 0:
>         #                 continue
> 
>         #         fn, label = l.strip().split('\t')
>         #         fn = root.parent.joinpath('images', fn)
>         #         self.items.append((str(fn), label))
> ```
> 
> 这段注释去掉，将`drive/My Drive/cv/images/dataset/labels.txt`改成你自己的`labels.txt`文件地址。这里面的训练数据和验证数据的数量比例是`20:1`，要按自己情况调整。
> 
> ### 第二步开始学习
> ```python
> model = OCRModel()
> model.evolution()
> model.save_checkpoint('path/to/your/model.pth')
> ```
> 
> 上面的学习步骤使用了默认参数。实际上除了`OCRModel`的`evolution`方法的参数可以自己定外，还有其他一些参数可以自己改，比如：
> 
> * 你可以修改`src/model/vocabulary.py`中的`vocabulary`，定义自己的字符集（分类）；
> * 你可以修改`OCRModel`的`input_shape`的`320`，假如你要识别的图片序列最长超过了20个字符（width=16*序列长度）；
> * 你可以修改`OCRModel`的`batch_size`。

谢谢您的回复！
我还是想问，我是需要再单独建立train.py文件吗？
修改完上面的参数后，在train.py中增加如下代码：
`import logging
from model.model import OCRModel
import cv2
import argparse
from pathlib import Path
from model import train
from model import model
if __name__ == '__main__':

    model = OCRModel()
    model.evolution()
    model.save_checkpoint('path/to/your/model.pth')


`
我见您的mode.py中有train()函数，直接在model.py文件中跑这个函数来可以吗？
能不能把您的train文件上传一下，我这边好多错误。

**Comment by zhangjingling** [comment]
> > ### 第一步准备数据
> > 先准备数据，然后制成一份索引文件，假设是`labels.txt`：
> > ```
> > dataset/123.jpg   123
> > dataset/2345.jpg  2345
> > ...
> > ```
> > 
> > 
> > 第一列是图片地址，第二列是标注，列和列之间用`'\t'`符分隔。然后在`src/model/dataset.py`源码中将：
> > ```python
> >         # 本地数据集
> >         # root=Path('drive/My Drive/cv/images/dataset/labels.txt')
> >         # line = 0
> >         # with open(root) as f:
> >         #     for l in f:
> >         #         line += 1
> >         #         if train:
> >         #             if line % 20 == 0:
> >         #                 continue
> >         #         else:
> >         #             if line % 20 != 0:
> >         #                 continue
> > 
> >         #         fn, label = l.strip().split('\t')
> >         #         fn = root.parent.joinpath('images', fn)
> >         #         self.items.append((str(fn), label))
> > ```
> > 
> > 
> > 这段注释去掉，将`drive/My Drive/cv/images/dataset/labels.txt`改成你自己的`labels.txt`文件地址。这里面的训练数据和验证数据的数量比例是`20:1`，要按自己情况调整。
> > ### 第二步开始学习
> > ```python
> > model = OCRModel()
> > model.evolution()
> > model.save_checkpoint('path/to/your/model.pth')
> > ```
> > 
> > 
> > 上面的学习步骤使用了默认参数。实际上除了`OCRModel`的`evolution`方法的参数可以自己定外，还有其他一些参数可以自己改，比如：
> > 
> > * 你可以修改`src/model/vocabulary.py`中的`vocabulary`，定义自己的字符集（分类）；
> > * 你可以修改`OCRModel`的`input_shape`的`320`，假如你要识别的图片序列最长超过了20个字符（width=16*序列长度）；
> > * 你可以修改`OCRModel`的`batch_size`。
> 
> 谢谢您的回复！
> 我还是想问，我是需要再单独建立train.py文件吗？
> 修改完上面的参数后，在train.py中增加如下代码：
> `import logging
> from model.model import OCRModel
> import cv2
> import argparse
> from pathlib import Path
> from model import train
> from model import model
> if **name** == '**main**':
> 
> ```
> model = OCRModel()
> model.evolution()
> model.save_checkpoint('path/to/your/model.pth')
> ```
> 
> `
> 我见您的mode.py中有train()函数，直接在model.py文件中跑这个函数来可以吗？
> 能不能把您的train文件上传一下，我这边好多错误。

我想利用代码识别别的图片中的所有数字，印刷体的数字

**Comment by zhangjingling** [comment]
> > > ### 第一步准备数据
> > > 先准备数据，然后制成一份索引文件，假设是`labels.txt`：
> > > ```
> > > dataset/123.jpg   123
> > > dataset/2345.jpg  2345
> > > ...
> > > ```
> > > 
> > > 
> > > 第一列是图片地址，第二列是标注，列和列之间用`'\t'`符分隔。然后在`src/model/dataset.py`源码中将：
> > > ```python
> > >         # 本地数据集
> > >         # root=Path('drive/My Drive/cv/images/dataset/labels.txt')
> > >         # line = 0
> > >         # with open(root) as f:
> > >         #     for l in f:
> > >         #         line += 1
> > >         #         if train:
> > >         #             if line % 20 == 0:
> > >         #                 continue
> > >         #         else:
> > >         #             if line % 20 != 0:
> > >         #                 continue
> > > 
> > >         #         fn, label = l.strip().split('\t')
> > >         #         fn = root.parent.joinpath('images', fn)
> > >         #         self.items.append((str(fn), label))
> > > ```
> > > 
> > > 
> > > 这段注释去掉，将`drive/My Drive/cv/images/dataset/labels.txt`改成你自己的`labels.txt`文件地址。这里面的训练数据和验证数据的数量比例是`20:1`，要按自己情况调整。
> > > ### 第二步开始学习
> > > ```python
> > > model = OCRModel()
> > > model.evolution()
> > > model.save_checkpoint('path/to/your/model.pth')
> > > ```
> > > 
> > > 
> > > 上面的学习步骤使用了默认参数。实际上除了`OCRModel`的`evolution`方法的参数可以自己定外，还有其他一些参数可以自己改，比如：
> > > 
> > > * 你可以修改`src/model/vocabulary.py`中的`vocabulary`，定义自己的字符集（分类）；
> > > * 你可以修改`OCRModel`的`input_shape`的`320`，假如你要识别的图片序列最长超过了20个字符（width=16*序列长度）；
> > > * 你可以修改`OCRModel`的`batch_size`。
> > 
> > 
> > 谢谢您的回复！
> > 我还是想问，我是需要再单独建立train.py文件吗？
> > 修改完上面的参数后，在train.py中增加如下代码：
> > `import logging
> > from model.model import OCRModel
> > import cv2
> > import argparse
> > from pathlib import Path
> > from model import train
> > from model import model
> > if **name** == '**main**':
> > ```
> > model = OCRModel()
> > model.evolution()
> > model.save_checkpoint('path/to/your/model.pth')
> > ```
> > 
> > 
> > `
> > 我见您的mode.py中有train()函数，直接在model.py文件中跑这个函数来可以吗？
> > 能不能把您的train文件上传一下，我这边好多错误。
> 
> 我想利用代码识别别的图片中的所有数字，印刷体的数字
你的数据集是单个数字的图片吗。类似minist？如果我想识别数字串，我是直接训练包含多个数字的图片，然后多个字符串做标签？

**Comment by HuangFJ** [comment]
我的训练数据是可变长度，但是这个库也支持用minist的数据，不矛盾。如果是印刷体我建议你直接用tesseract ocr，它支持用字体文件来做训练。用这个库来训练，提供不了那么多的训练数据。

**Comment by zhangjingling** [comment]
> 我的训练数据是可变长度，但是这个库也支持用minist的数据，不矛盾。如果是印刷体我建议你直接用tesseract ocr，它支持用字体文件来做训练。用这个库来训练，提供不了那么多的训练

**Comment by zhangjingling** [comment]
多谢哈，我已经训练出模型了。其实我就是想实现不定长数字串的识别，我先用我的数据跑一下

**Comment by zhangjingling** [comment]
![waterRuler_00140](https://user-images.githubusercontent.com/16750600/103197498-16312500-4921-11eb-9320-27dd3ccdaed8.jpg)


我想识别这种图片中的所有数据，输出数字串即可。那我是直接用这种数据做数据集，数字串做标签，效果好，还是印刷体只含1,2,3,4的数据做数据集？
